PREFIX kgi: <http://ns.inria.fr/kg/index#>
PREFIX earl: <http://www.w3.org/ns/earl#>
PREFIX prov: <http://www.w3.org/ns/prov#>

INSERT {
    GRAPH kgi:Logs {
        kgi:Logs kgi:trace [
            earl:result [
                    earl:outcome earl:failed ;
                    kgi:sentQuery $query ;
                    prov:wasGeneratedAtTime $endTime ;
                    earl:info $reason
                ] ;
            earl:subject $rawEndpointUrl ;
            earl:test $test ;
            prov:startedAtTime $startTime ;
            prov:endedAtTime $endTime
        ]
    }
} WHERE {
    BIND(Iri(CONCAT(str(kgi:), "Logs") ) AS ?logGraph)
}
