services:
  corese:
    image: secoresearch/fuseki:5.5.0
    hostname: corese
    environment:
      TDB: "2"
      QUERY_TIMEOUT: "240000"
      ENABLE_UPDATE: "true"
      ENABLE_DATA_WRITE: "true"
      ADMIN_PASSWORD: "admin"
    expose: 
      - "3030"
    volumes:
      # - ./input:/input
      # - ./data:/fuseki-base/databases
      - ./output:/output
      - ./config:/fuseki-configuration
      - ./rules:/rules
    extra_hosts:
      - host.docker.internal:host-gateway
  indegx:
    build: .
    depends_on:
      - corese
    volumes:
      - ./input:/input
      - ./output:/output
      - ./config:/config
      - ./catalogs:/catalogs
      - ./rules:/rules
    environment:
      - INDEGX_ARGS=${INDEGX_ARGS}