PREFIX kgi: <http://ns.inria.fr/kg/index#>
PREFIX earl: <http://www.w3.org/ns/earl#>
PREFIX prov: <http://www.w3.org/ns/prov#>

INSERT {
    GRAPH ?metadataDescriptionGraph {
        ?metadataDescription kgi:trace [
            earl:result [
                    earl:outcome earl:failed ;
                    kgi:sentQuery $query ;
                    prov:wasGeneratedAtTime $endTime ;
                    earl:info $reason
                ] ;
            earl:subject ?endpointDescription ;
            earl:test $test ;
            prov:startedAtTime $startTime ;
            prov:endedAtTime $endTime
        ]
    }
} WHERE {
    BIND(Iri(CONCAT(str(kgi:), MD5(str($rawEndpointUrl)), "Metadata")) AS ?metadataDescription)
    BIND(Iri(CONCAT(str(kgi:), MD5(str($rawEndpointUrl)), "Endpoint")) AS ?endpointDescription)
    BIND(Iri(CONCAT("http://ns.inria.fr/kg/index#", MD5(str($rawEndpointUrl)), "_", DAY(NOW()), "-", MONTH(NOW()), "-", YEAR(NOW()) , "_" , "Metadata")) AS ?metadataDescriptionGraph)
}
