PREFIX void: <http://www.w3.org/2002/07/owl#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX kgi: <http://ns.inria.fr/kg/index#>
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
PREFIX pav: <http://purl.org/pav/>

CONSTRUCT {
    ?dataset dcat:endpointURL ?sparql ; 
        pav:importedFrom <SOURCE> .
} WHERE {
    {
        ?s ?p ?URL .
    } UNION {
        GRAPH ?g {
            ?s ?p ?URL .
        }
    }
    BIND(IRI(STR(?URL)) as ?sparql)
    FILTER (?p IN (void:sparqlEndpoint, dcat:endpointURL, sd:endpoint))
    BIND (IRI(CONCAT(STR(kgi:), ENCODE_FOR_URI(?sparql))) AS ?dataset)
}