PREFIX void: <http://rdfs.org/ns/void#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX kgi: <http://ns.inria.fr/kg/index#>
PREFIX sd: <http://www.w3.org/ns/sparql-service-description#>
PREFIX pav: <http://purl.org/pav/>

CONSTRUCT {
    kgi:Catalog a dcat:Catalog ;
        pav:lastRefreshedOn ?date .
} WHERE {
    BIND( NOW() as ?date )
}