PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?class {
    { ?class a owl:Class }
    UNION { ?class a rdfs:Class }
    FILTER(ISIRI(?class))
}