PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?namespace_string {
    ?vocab a owl:Ontology .
    OPTIONAL {
        ?vocab vann:preferredNamespaceUri ?namespace .
    }
    FILTER( isIRI(?vocab))
    BIND( REPLACE( REPLACE( IF( BOUND(?namespace), STR(?namespace), STR(?vocab)), "#$", ""), "/$", "") AS ?namespace_string)
}