# This is a basic workflow that is manually triggered

name: Auto Catalog Refresh Script
on:
    schedule:
      - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  auto_catalog_refresh_script:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Script launch
      working-directory: ./scripts/auto_catalog_refresh
      run: ./script.sh
    - name: Copy the resulting catalog
      run: cp ./scripts/auto_catalog_refresh/catalog.final.trig ./catalogs/catalog.auto_refresh.trig
    - name: Commit files
      run: |
        git add ./catalogs/catalog.auto_refresh.trig -f
        git config --local user.email "pierre.maillot@inria.fr"
        git config --local user.name "Pierre Maillot"
        git commit -m "Automatic catalog update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: catalog_auto_refresh