name: Update SPARQL Endpoint Service Status
on:
    workflow_dispatch:
    schedule:
    - cron: '40 * * * *' # every hour
jobs:
    update-sparql-endpoint-status:
        runs-on: ubuntu-latest
        name: Update SPARQL Endpoint Service Status
        steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: endpoint_status
        - name: Run service check
          working-directory: ./scripts/endpoint_status
          run: ./script.sh
        - name: Add & Commit
          uses: EndBug/add-and-commit@v9.1.3
          with:
            add: 'catalogs/catalog.latest-status.ttl'
            message: 'Automatic status update'
            author_name: 'Pierre Maillot'
            author_email: 'pierre.maillot@inria.fr'
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: endpoint_status
    
    